from os.path import join

from gen_common_test.base.paths.base_paths import GEN_COMMON_TEST_DATA_PATH

# Prompts
GEN_COMMON_TEST_PROMPT_JSONL_PATH = join(GEN_COMMON_TEST_DATA_PATH, "repo")
# Repo
GEN_COMMON_TEST_PROJECT_REPO_PATH = join(GEN_COMMON_TEST_DATA_PATH, "repo")
GEN_COMMON_TEST_PROJECT_REPO_ONE_PATH = join(GEN_COMMON_TEST_PROJECT_REPO_PATH, "one")
GEN_COMMON_TEST_PROJECT_REPO_TWO_PATH = join(GEN_COMMON_TEST_PROJECT_REPO_PATH, "two")
# Structure
GEN_COMMON_TEST_PROJECT_STRUCTURE_PATH = join(GEN_COMMON_TEST_DATA_PATH, "structure")
# CSV
GEN_COMMON_TEST_PROJECT_CSV_PATH = join(GEN_COMMON_TEST_DATA_PATH, "csv", "test_csv_data.csv")
# SAFA
GEN_COMMON_TEST_PROJECT_SAFA_PATH = join(GEN_COMMON_TEST_DATA_PATH, "safa")
# PreTrainTrace
GEN_COMMON_TEST_PROJECT_PRETRAIN_PATH = join(GEN_COMMON_TEST_DATA_PATH, "pre_train_trace", "handbook.txt")
# Data Frame
GEN_COMMON_TEST_PROJECT_DATAFRAME_PATH = join(GEN_COMMON_TEST_DATA_PATH, "dataframe")
# prompt
GEN_COMMON_TEST_PROMPT_LHP_PATH = join(GEN_COMMON_TEST_DATA_PATH, "prompt", "lhp.jsonl")
GEN_COMMON_TEST_PROMPT_SAFA_PATH = join(GEN_COMMON_TEST_DATA_PATH, "prompt", "safa_proj.jsonl")
# github
GEN_COMMON_TEST_GITHUB_PATH = join(GEN_COMMON_TEST_DATA_PATH, "github")
COMMON_TEST_GITHUB_ARTIFACTS_PATH = join(GEN_COMMON_TEST_GITHUB_PATH, "artifacts")
# Chunks
GEN_COMMON_TEST_PROJECT_CHUNK_PATH = join(GEN_COMMON_TEST_DATA_PATH, "chunker")
GEN_COMMON_TEST_PROJECT_CHUNK_TESTJAVA_PATH = join(GEN_COMMON_TEST_PROJECT_CHUNK_PATH, "test_java.java")
GEN_COMMON_TEST_PROJECT_CHUNK_TESTPYTHON_PATH = join(GEN_COMMON_TEST_DATA_PATH, "chunker/test_python.py")
# PreTrain
GEN_COMMON_TEST_PRE_TRAIN_PATH = join(GEN_COMMON_TEST_DATA_PATH, "pre_train")
# hgen
GEN_COMMON_TEST_HGEN_PATH = join(GEN_COMMON_TEST_DATA_PATH, "hgen")
# state
GEN_COMMON_TEST_STATE_PATH = join(GEN_COMMON_TEST_DATA_PATH, "state")
# Result reader
GEN_COMMON_TEST_RESULT_READER_PATH = join(GEN_COMMON_TEST_DATA_PATH, "result_reader")
# Cleaning
GEN_COMMON_TEST_PROJECT_CLEANING_PATH = join(GEN_COMMON_TEST_DATA_PATH, "cleaning")
GEN_COMMON_TEST_CLEANING_CPP = join(GEN_COMMON_TEST_PROJECT_CLEANING_PATH, "test.hpp")
GEN_COMMON_TEST_CLEANING_JAVA = join(GEN_COMMON_TEST_PROJECT_CLEANING_PATH, "test.java")
