import { MemberRole, MembershipType, PermissionType } from "@/types";

/**
 * A map of all app roles and permissions.
 */
export const roleMap: Record<
  MembershipType,
  Record<MemberRole, PermissionType[]>
> = {
  PROJECT: {
    PENDING: [],
    NONE: [],
    VIEWER: ["project.view"],
    EDITOR: ["project.view", "project.edit", "project.edit_data"],
    GENERATOR: [
      "project.view",
      "project.edit",
      "project.edit_data",
      "project.generate",
    ],
    ADMIN: [
      "project.view",
      "project.edit",
      "project.edit_data",
      "project.generate",
      "project.edit_members",
      "project.edit_integrations",
      "project.edit_versions",
    ],
    OWNER: [
      "project.view",
      "project.edit",
      "project.edit_data",
      "project.generate",
      "project.edit_members",
      "project.edit_integrations",
      "project.edit_versions",
      "project.delete",
    ],
    MEMBER: [],
    BILLING_MANAGER: [],
  },
  TEAM: {
    PENDING: [],
    NONE: [],
    VIEWER: ["project.view", "team.view", "team.view_projects"],
    EDITOR: [
      "project.view",
      "project.edit",
      "project.edit_data",
      "project.edit_members",
      "project.edit_integrations",
      "project.edit_versions",
      "team.view",
      "team.view_projects",
    ],
    GENERATOR: [
      "project.view",
      "project.edit",
      "project.edit_data",
      "project.generate",
      "project.edit_members",
      "project.edit_integrations",
      "project.edit_versions",
      "team.view",
      "team.view_projects",
    ],
    ADMIN: [
      "project.view",
      "project.delete",
      "project.edit",
      "project.edit_data",
      "project.generate",
      "project.edit_members",
      "project.edit_integrations",
      "project.edit_versions",
      "team.view",
      "team.edit",
      "team.edit_members",
      "team.view_projects",
      "team.create_projects",
      "team.delete_projects",
    ],
    OWNER: [],
    MEMBER: [],
    BILLING_MANAGER: [],
  },
  ORGANIZATION: {
    PENDING: [],
    NONE: [],
    VIEWER: ["org.view", "org.view_teams"],
    EDITOR: [],
    GENERATOR: ["org.view", "org.view_teams", "project.generate"],
    ADMIN: [
      "org.view",
      "org.view_teams",
      "project.generate",
      "org.edit",
      "org.edit_members",
      "org.delete_teams",
      "org.create_teams",
    ],
    OWNER: [],
    MEMBER: [],
    BILLING_MANAGER: ["org.view", "org.view_billing"],
  },
};
