AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EnvReaderManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'envs-reader-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Action:
          - 's3:GetObject'
          - 's3:PutObject'
          - 's3:PutObjectAcl'
          Resource: 'arn:aws:s3:::safa-envs/*'

  ExecutionPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'general-execution-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Action:
          - ec2:*
          - ecs:*
          - elasticfilesystem:*
          - codebuild:*
          - codecommit:*
          - codepipeline:*
          - codestar:*
          - codestar-connections:*
          - cloudwatch:*
          - ecr:*
          - s3:*
          - secretsmanager:*
          - logs:*
          Resource: '*'