<template>
  <private-page small-window>
    <flex-box :column="smallWindow" full-width>
      <flex-item v-if="displayDemo" style="width: 80vw">
        <panel-card title="Public SAFA Projects" icon="nav-open">
          <typography
            variant="small"
            value="Browse through our collection of public datasets with documentation generated by SAFA."
          />
          <project-version-stepper minimal />
        </panel-card>
      </flex-item>

      <flex-item v-if="displayProjects" :parts="smallWindow ? '12' : '7'">
        <div :class="smallWindow ? '' : 'q-mr-md'">
          <panel-card title="Load Existing Project" icon="nav-open">
            <typography
              variant="small"
              value="Select an existing project and version to load."
            />
            <project-version-stepper minimal />
          </panel-card>
        </div>
      </flex-item>

      <flex-item
        v-if="!displayDemo"
        :parts="smallWindow || !displayProjects ? '12' : '5'"
      >
        <panel-card title="Create New Project" icon="project-add">
          <typography
            variant="small"
            value="Chose which data source you would like to create a project from."
          />
          <flex-box full-width justify="center" t="2">
            <flex-box column>
              <text-button
                text
                label="Import From GitHub"
                icon="integrate"
                color="primary"
                @click="handleOpenImport"
              />
              <text-button
                text
                label="Upload From Files"
                icon="upload"
                color="primary"
                @click="handleOpenBulk"
              />
            </flex-box>
          </flex-box>
        </panel-card>
        <external-links />
      </flex-item>
    </flex-box>
  </private-page>
</template>

<script lang="ts">
/**
 * Displays the home page.
 */
export default {
  name: "HomeView",
};
</script>

<script setup lang="ts">
import { computed } from "vue";
import { CreatorTab } from "@/types";
import { permissionStore, projectStore, useScreen } from "@/hooks";
import { navigateTo, QueryParams, Routes } from "@/router";
import {
  ExternalLinks,
  PrivatePage,
  FlexBox,
  Typography,
  PanelCard,
  TextButton,
  ProjectVersionStepper,
  FlexItem,
} from "@/components";

const { smallWindow } = useScreen();

const displayDemo = computed(() => permissionStore.isDemo);
const displayProjects = computed(
  () => !displayDemo.value && projectStore.allProjects.length > 0
);

function handleOpenBulk() {
  navigateTo(Routes.PROJECT_CREATOR, {
    [QueryParams.TAB]: "bulk" as CreatorTab,
  });
}

function handleOpenImport() {
  navigateTo(Routes.PROJECT_CREATOR, {
    [QueryParams.TAB]: "import" as CreatorTab,
  });
}
</script>
