steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--progress=plain',
            '--build-arg', 'DB_INSTANCE=${_DB_INSTANCE}',
            '--build-arg', 'DB_USER=${_DB_USER}',
            '--build-arg', 'DB_PASSWORD=${_DB_PASSWORD}',
            '--build-arg', 'DB_URL=${_DB_URL}',
            '--build-arg', 'JWT_KEY=${_JWT_KEY}',
            '--build-arg', 'JIRA_CLIENT_ID=${_JIRA_CLIENT_ID}',
            '--build-arg', 'JIRA_SECRET=${_JIRA_SECRET}',
            '--build-arg', 'JIRA_REDIRECT_LINK=${_JIRA_REDIRECT_LINK}',
            '--build-arg', 'GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID}',
            '--build-arg', 'GITHUB_SECRET=${_GITHUB_SECRET}',
            '.' ]

timeout: 800s
