steps:
  # Build the container image and toss result
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--build-arg', 'DB_HOST=${_DB_HOST}',
            '--build-arg', 'DB_USER=${_DB_USER}',
            '--build-arg', 'DB_PASSWORD=${_DB_PASSWORD}',
            '.' ]
