steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: [
        "build",
        "--build-arg", "API_ENDPOINT=${_API_ENDPOINT}",
        "--build-arg", "JIRA_CLIENT_ID=${_JIRA_CLIENT_ID}",
        "--build-arg", "JIRA_CLIENT_SECRET=${_JIRA_CLIENT_SECRET}",
        "--build-arg", "JIRA_REDIRECT_LINK=${_JIRA_REDIRECT_LINK}",
        "-t", "gcr.io/$PROJECT_ID/safa-fend-${_STAGE}",
        "."
    ]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/safa-fend-${_STAGE}"]
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [ "run", "deploy", "${_SERVICE_NAME}", "--image", "gcr.io/$PROJECT_ID/safa-fend-${_STAGE}", "--region", "${_REGION}"]
images:
  - gcr.io/$PROJECT_ID/safa-fend-${_STAGE}

timeout: 900s
