steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the container image'
    args: [
      'build',
      '--push',
      '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA',
      '.'
    ]

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy container image to Cloud Run'
    entrypoint: gcloud
    args: ['run', 'deploy', '$_SERVICE_NAME',
           '--image', 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA',
           '--region', '$_REGION',
           '--platform', 'managed']
images:
  - 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA'
