steps:
  - name: 'bash'
    args: ['touch', '.env']
  - name: 'bash'
    args: ['touch', 'safa-google-key.json']
  - name: 'bash'
    args:
      - 'env'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg', '_MY_SQL_HOST=${_MY_SQL_HOST}',
           '--build-arg', '_MY_SQL_USERNAME=${_MY_SQL_USERNAME}',
           '--build-arg', '_MY_SQL_PASSWORD=${_MY_SQL_PASSWORD}',
           '--build-arg', '_MY_SQL_CONNECTION_NAME=${_MY_SQL_CONNECTION_NAME}',
           '--build-arg', '_MY_SQL_DATABASE=${_MY_SQL_DATABASE}',
           '--build-arg', '_NEO4J_URI=${_NEO4J_URI}',
           '--build-arg', '_NEO4J_USERNAME=${_NEO4J_USERNAME}',
           '--build-arg', '_NEO4J_PASSWORD=${_NEO4J_PASSWORD}',
           '.',
    ]
