steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build',
            '--progress=plain',
            '--build-arg', 'DB_INSTANCE_ARG=${_DB_INSTANCE}',
            '--build-arg', 'DB_USER_ARG=${_DB_USER}',
            '--build-arg', 'DB_PASSWORD_ARG=${_DB_PASSWORD}',
            '--build-arg', 'DB_URL_ARG=${_DB_URL}',
            '--build-arg', 'JWT_KEY_ARG=${_JWT_KEY}',
            '--build-arg', 'JIRA_CLIENT_ID_ARG=${_JIRA_CLIENT_ID}',
            '--build-arg', 'JIRA_SECRET_ARG=${_JIRA_SECRET}',
            '--build-arg', 'JIRA_REDIRECT_LINK_ARG=${_JIRA_REDIRECT_LINK}',
            '--build-arg', 'GITHUB_CLIENT_ID_ARG=${_GITHUB_CLIENT_ID}',
            '--build-arg', 'GITHUB_SECRET_ARG=${_GITHUB_SECRET}',
            '-t', 'gcr.io/$PROJECT_ID/safa-bend-${_STAGE}',
            '.' ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/safa-bend-${_STAGE}' ]

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', '${_SERVICE_NAME}','--image', 'gcr.io/$PROJECT_ID/safa-bend-${_STAGE}','--region', '${_REGION}' ]

images:
  - gcr.io/$PROJECT_ID/safa-bend-${_STAGE}
timeout: 1200s
