steps:
  # Build the container image with cacheing
  - name: 'gcr.io/kaniko-project/executor:latest'
    args: ['--build-arg', 'BUCKET=${_BUCKET}', '--snapshotMode=redo', '--destination=gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}' ,'--cache=true', '--cache-ttl=72h']
    env:
      - "DOCKER_BUILDKIT=1"
      - "IFS=''"
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', '${_SERVICE_NAME}', '--container-image','gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}', '--zone', '${_ZONE}' ]
options:
  machineType: 'e2-standard-4'
timeout: 1200s
