steps:
  - name: 'bash'
    args: ['touch', '.env']
  - name: 'bash'
    args: ['touch', 'safa-google-key.json']
  - name: 'bash'
    args:
      - 'env'
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '.'
