steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '--build-arg', 'DB_USER=${_DB_USER}','--build-arg', 'DB_PASSWORD=${_DB_PASSWORD}', '--build-arg', 'DB_URL=${_DB_URL}','-t','gcr.io/$PROJECT_ID/safa-bend-${_STAGE}','.' ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/safa-bend-${_STAGE}' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', '${_SERVICE_NAME}','--image', 'gcr.io/$PROJECT_ID/safa-bend-${_STAGE}','--region', '${_REGION}' ]
images:
  - gcr.io/$PROJECT_ID/safa-bend-${_STAGE}
