steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build the container image'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA',
      '.'
    ]

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push the container image to Container Registry'
    args: ['push', 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/$BRANCH_NAME/$COMMIT_SHA'
