steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [  'build', '--progress=plain', '--build-arg', 'BUCKET=${_BUCKET}', '-t','gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}', '.' ]
    env:
      - "DOCKER_BUILDKIT=1"
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}' ]
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [ 'run', 'deploy', '${_SERVICE_NAME}','--image', 'gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}','--region', '${_REGION}' ]
images:
  - gcr.io/$PROJECT_ID/safa-tgen-${_STAGE}
timeout: 800s
