version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    # Check the npm registry for updates at 2am UTC
    schedule:
      interval: "daily"
      time: "02:00"
    # Raise all npm pull requests with reviewers
    reviewers:
      - "imanewman"
    # Raise all npm pull requests with an assignee
    assignees:
      - "imanewman"
