[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tgen"
version = "0.0.1"
authors = [
  { name="Kat Dearstyne", email="kat@safa.ai" },
  { name="Alberto Rodriguez", email="alberto@safa.ai" },
]
description = "Trace Generation for SAFA.ai"
readme = "README.md"
requires-python = ">=3.7"