AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
    NoEcho: true
    Description: 'ID of VPC containing security group.'

Resources:
  DatabaseConnectorSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'database-connector'
      GroupDescription: Security group for database connector
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0

  LoadBalancersSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'load-balancer'
      GroupDescription: Security group for load balancers
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0

  InstancesSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'instance'
      GroupDescription: Security group for instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: '-1'
        SourceSecurityGroupId: !GetAtt LoadBalancersSecurityGroup.GroupId
      SecurityGroupEgress:
      - IpProtocol: '-1'
        CidrIp: 0.0.0.0/0

  PrivateSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 'private'
      GroupDescription: Security group for private instances
      VpcId: !Ref VpcId
      SecurityGroupIngress:
      - IpProtocol: '-1'
        SourceSecurityGroupId: !GetAtt InstancesSecurityGroup.GroupId
      - IpProtocol: '-1'
        SourceSecurityGroupId: !GetAtt DatabaseConnectorSecurityGroup.GroupId
      SecurityGroupEgress: []
