/**
 * A mapping of whether certain test features are enabled.
 */
export const ENABLED_FEATURES = {
  ARTIFACT_PROMPTS: false,
  ARTIFACT_NAME_CHECK: false,

  ACTIVE_USERS: false,
  TRACE_MATRIX_TABLE: false,

  ONBOARDING_PUBLIC_REPOS: false,

  GENERATE_SUMMARIES: false,

  SIGN_UP: true,

  NASA_ARTIFACT_COMMENT: true,
  NASA_ARTIFACT_COMMENT_MOCKUP: false,
  NASA_ARTIFACT_HEALTH: true,
  NASA_ARTIFACT_HEALTH_NEW: false,
  NASA_ARTIFACT_HEALTH_PRELOAD: false,
  NASA_ARTIFACT_RELATIONS: true,
  NASA_PROJECT_CHAT: true,
  NASA_PROJECT_CHAT_MOCKUP: false,
};
