//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for ATTRIBUTE-VALUE-XHTML complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUTE-VALUE-XHTML", namespace = "", propOrder = {})
@Getter
@Setter
public class AttributeValueXhtml extends AttributeValue {

    @XmlElement(name = "THE-VALUE", required = true)
    private XhtmlContent value;

    @XmlElement(name = "THE-ORIGINAL-VALUE")
    private XhtmlContent originalValue;

    @XmlElement(name = "DEFINITION", required = true)
    private Definition definition;

    @XmlAttribute(name = "IS-SIMPLIFIED")
    private Boolean simplified;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeDefinition"
    })
    @Getter
    @Setter
    public static class Definition {
        @XmlElement(name = "ATTRIBUTE-DEFINITION-XHTML-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private AttributeDefinitionXhtml attributeDefinition;
    }

}
