//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 06:07:33 PM UTC 
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

import lombok.Getter;
import lombok.Setter;

/**
 * Java class for ATTRIBUTE-DEFINITION-DATE complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUTE-DEFINITION-DATE", namespace = "", propOrder = {})
@Getter
@Setter
public class AttributeDefinitionDate extends AttributeDefinition {

    @XmlElement(name = "DEFAULT-VALUE")
    protected DefaultValue defaultValue;

    @XmlElement(name = "TYPE", required = true)
    protected Type type;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeValue"
    })
    @Getter
    @Setter
    public static class DefaultValue {
        @XmlElement(name = "ATTRIBUTE-VALUE-DATE", namespace = "")
        protected AttributeValueDate attributeValue;
    }


    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "datatypeDefinition"
    })
    @Getter
    @Setter
    public static class Type {
        @XmlElement(name = "DATATYPE-DEFINITION-DATE-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected DatatypeDefinitionDate datatypeDefinition;
    }

}
