//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 04:50:11 PM UTC 
//


package edu.nd.crc.safa.utilities.reqif.datatypes;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ATTRIBUTE-VALUE-STRING complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ATTRIBUTE-VALUE-STRING"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="DEFINITION"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice&gt;
 *                   &lt;element name="ATTRIBUTE-DEFINITION-STRING-REF" type="{http://www.omg.org/spec/ReqIF/20110401/reqif.xsd}LOCAL-REF"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *       &lt;attribute name="THE-VALUE" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUTE-VALUE-STRING", namespace = "http://www.omg.org/spec/ReqIF/20110401/reqif.xsd", propOrder = {

})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
public class AttributeValueString {

    @XmlElement(name = "DEFINITION", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected AttributeValueString.DEFINITION definition;
    @XmlAttribute(name = "THE-VALUE", required = true)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String thevalue;

    /**
     * Gets the value of the definition property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeValueString.DEFINITION }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public AttributeValueString.DEFINITION getDEFINITION() {
        return definition;
    }

    /**
     * Sets the value of the definition property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeValueString.DEFINITION }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setDEFINITION(AttributeValueString.DEFINITION value) {
        this.definition = value;
    }

    /**
     * Gets the value of the thevalue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getTHEVALUE() {
        return thevalue;
    }

    /**
     * Sets the value of the thevalue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setTHEVALUE(String value) {
        this.thevalue = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice&gt;
     *         &lt;element name="ATTRIBUTE-DEFINITION-STRING-REF" type="{http://www.omg.org/spec/ReqIF/20110401/reqif.xsd}LOCAL-REF"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributedefinitionstringref"
    })
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public static class DEFINITION {

        @XmlElement(name = "ATTRIBUTE-DEFINITION-STRING-REF", namespace = "http://www.omg.org/spec/ReqIF/20110401/reqif.xsd")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
        protected Object attributedefinitionstringref;

        /**
         * Gets the value of the attributedefinitionstringref property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
        public Object getATTRIBUTEDEFINITIONSTRINGREF() {
            return attributedefinitionstringref;
        }

        /**
         * Sets the value of the attributedefinitionstringref property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
        public void setATTRIBUTEDEFINITIONSTRINGREF(Object value) {
            this.attributedefinitionstringref = value;
        }

    }

}
