//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 06:07:33 PM UTC 
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.Getter;
import lombok.Setter;

/**
 * Java class for ATTRIBUTE-VALUE-DATE complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUTE-VALUE-DATE", namespace = "", propOrder = {})
@Getter
@Setter
public class AttributeValueDate extends AttributeValue {

    @XmlElement(name = "DEFINITION", required = true)
    private Definition definition;

    @XmlAttribute(name = "THE-VALUE", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar value;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeDefinition"
    })
    @Getter
    @Setter
    public static class Definition {
        @XmlElement(name = "ATTRIBUTE-DEFINITION-DATE-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private AttributeDefinitionDate attributeDefinition;
    }

}
