//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for DATATYPE-DEFINITION-ENUMERATION complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATATYPE-DEFINITION-ENUMERATION", namespace = "", propOrder = {})
@Getter
@Setter
public class DatatypeDefinitionEnumeration extends DatatypeDefinition {

    @XmlElement(name = "SPECIFIED-VALUES")
    private SpecifiedValues specifiedValues;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "values"
    })
    @Getter
    public static class SpecifiedValues {
        @XmlElement(name = "ENUM-VALUE", namespace = "")
        private List<EnumValue> values = new ArrayList<>();
    }

}
