//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.Getter;
import lombok.Setter;


/**
 * Java class for RELATION-GROUP complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RELATION-GROUP", namespace = "", propOrder = {})
@Getter
@Setter
public class RelationGroup {

    @XmlElement(name = "ALTERNATIVE-ID")
    private AlternativeIdWrapper alternativeId;

    @XmlElement(name = "SOURCE-SPECIFICATION", required = true)
    private SpecificationRef sourceSpecification;

    @XmlElement(name = "SPEC-RELATIONS")
    private SpecRelations specRelations;

    @XmlElement(name = "TARGET-SPECIFICATION", required = true)
    private SpecificationRef targetSpecification;

    @XmlElement(name = "TYPE", required = true)
    private Type type;

    @XmlAttribute(name = "DESC")
    private String desc;

    @XmlAttribute(name = "IDENTIFIER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    private String identifier;

    @XmlAttribute(name = "LAST-CHANGE", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar lastChange;

    @XmlAttribute(name = "LONG-NAME")
    private String longName;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specRelations"
    })
    @Getter
    public static class SpecRelations {
        @XmlElementRef(type = SpecRelationRef.class, required = false)
        private List<SpecRelationRef> specRelations = new ArrayList<>();
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlRootElement(name = "SPEC-RELATION-REF", namespace = "")
    @Getter
    @Setter
    public static class SpecRelationRef {
        @XmlValue
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private SpecRelation specRelation;
    }

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "type"
    })
    @Getter
    @Setter
    public static class Type {
        @XmlElement(name = "RELATION-GROUP-TYPE-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private RelationGroupType type;
    }

}
