//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 06:07:33 PM UTC 
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.Getter;
import lombok.Setter;

/**
 * Java class for REQ-IF-HEADER complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQ-IF-HEADER", namespace = "", propOrder = {
    "comment",
    "creationTime",
    "repositoryId",
    "reqIfToolId",
    "reqIfVersion",
    "sourceToolId",
    "title"
})
@Getter
@Setter
public class ReqIfHeader {

    @XmlElement(name = "COMMENT")
    protected String comment;

    @XmlElement(name = "CREATION-TIME", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar creationTime;

    @XmlElement(name = "REPOSITORY-ID")
    protected String repositoryId;

    @XmlElement(name = "REQ-IF-TOOL-ID", required = true)
    protected String reqIfToolId;

    @XmlElement(name = "REQ-IF-VERSION", required = true)
    protected String reqIfVersion;

    @XmlElement(name = "SOURCE-TOOL-ID", required = true)
    protected String sourceToolId;

    @XmlElement(name = "TITLE", required = true)
    protected String title;

    @XmlAttribute(name = "IDENTIFIER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;
}
