//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 06:07:33 PM UTC 
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlIDREF;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;

import lombok.Getter;
import lombok.Setter;

/**
 * Java class for SPEC-HIERARCHY complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPEC-HIERARCHY", namespace = "", propOrder = {})
@Getter
@Setter
public class SpecHierarchy {

    @XmlElement(name = "ALTERNATIVE-ID")
    protected AlternativeIdWrapper alternativeId;

    @XmlElement(name = "CHILDREN")
    protected Children children;

    @XmlElement(name = "EDITABLE-ATTS")
    protected EditableAttributes editableAttributes;

    @XmlElement(name = "OBJECT", required = true)
    protected ObjectRef object;

    @XmlAttribute(name = "DESC")
    protected String desc;

    @XmlAttribute(name = "IDENTIFIER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String identifier;

    @XmlAttribute(name = "IS-EDITABLE")
    protected Boolean editable;

    @XmlAttribute(name = "IS-TABLE-INTERNAL")
    protected Boolean tableInternal;

    @XmlAttribute(name = "LAST-CHANGE", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastChange;

    @XmlAttribute(name = "LONG-NAME")
    protected String longName;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeDefinitions"
    })
    @Getter
    public static class EditableAttributes {

        @XmlElementRefs({
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-BOOLEAN-REF",
                type = AttributeDefinitionBooleanRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-DATE-REF",
                type = AttributeDefinitionDateRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-ENUMERATION-REF",
                type = AttributeDefinitionEnumerationRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-INTEGER-REF",
                type = AttributeDefinitionIntegerRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-REAL-REF",
                type = AttributeDefinitionRealRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-STRING-REF",
                type = AttributeDefinitionStringRef.class, required = false),
            @XmlElementRef(name = "ATTRIBUTE-DEFINITION-XHTML-REF",
                type = AttributeDefinitionXhtmlRef.class, required = false)
        })
        protected List<AttributeDefinitionRef> attributeDefinitions = new ArrayList<>();
    }

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specObject"
    })
    @Getter
    @Setter
    public static class ObjectRef {

        @XmlElement(name = "SPEC-OBJECT-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        protected SpecObject specObject;
    }

}
