//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for xhtml.ol.type complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.ol.type", propOrder = {
    "content"
})
@XmlRootElement(name = "ol", namespace = "http://www.w3.org/1999/xhtml")
@Getter
@Setter
public class XhtmlOlType extends XhtmlBasicStyleableType {

    @XmlElement(required = true)
    @Setter(AccessLevel.NONE)
    private List<XhtmlLiType> content = new ArrayList<>();

}
