//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for xhtml.blockquote.type complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.blockquote.type", propOrder = {
    "content"
})
@XmlRootElement(name = "blockquote", namespace = "http://www.w3.org/1999/xhtml")
@Getter
@Setter
public class XhtmlBlockquoteType extends XhtmlBasicStyleableType {

    @XmlElementRefs({
        @XmlElementRef(type = XhtmlH1Type.class, required = false),
        @XmlElementRef(type = XhtmlH2Type.class, required = false),
        @XmlElementRef(type = XhtmlH3Type.class, required = false),
        @XmlElementRef(type = XhtmlH4Type.class, required = false),
        @XmlElementRef(type = XhtmlH5Type.class, required = false),
        @XmlElementRef(type = XhtmlH6Type.class, required = false),
        @XmlElementRef(type = XhtmlUlType.class, required = false),
        @XmlElementRef(type = XhtmlOlType.class, required = false),
        @XmlElementRef(type = XhtmlDlType.class, required = false),
        @XmlElementRef(type = XhtmlPType.class, required = false),
        @XmlElementRef(type = XhtmlDivType.class, required = false),
        @XmlElementRef(type = XhtmlPreType.class, required = false),
        @XmlElementRef(type = XhtmlBlockquoteType.class, required = false),
        @XmlElementRef(type = XhtmlAddressType.class, required = false),
        @XmlElementRef(type = XhtmlHrType.class, required = false),
        @XmlElementRef(type = XhtmlTableType.class, required = false),
        @XmlElementRef(type = XhtmlInsType.class, required = false),
        @XmlElementRef(type = XhtmlDelType.class, required = false)
    })
    @Setter(AccessLevel.NONE)
    private List<XhtmlBasicType> content = new ArrayList<>();

    @XmlAttribute(name = "cite")
    private String cite;

}
