//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 06:07:33 PM UTC 
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for xhtml.colgroup.type complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.colgroup.type", propOrder = {
    "col"
})
@Getter
@Setter
public class XhtmlColgroupType {

    @Setter(AccessLevel.NONE)
    protected List<XhtmlColType> col = new ArrayList<>();

    @XmlAttribute(name = "span")
    protected BigInteger span = BigInteger.ONE;

    @XmlAttribute(name = "width")
    @Setter(AccessLevel.NONE)
    protected List<String> width = new ArrayList<>();

    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    protected String lang;

    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String space = "preserve";

    @XmlAttribute(name = "class")
    protected String clazz;

    @XmlAttribute(name = "title")
    protected String title;

    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    protected String id;

    @XmlAttribute(name = "style")
    protected String style;

    @XmlAttribute(name = "valign")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String valign;

    @XmlAttribute(name = "align")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String align;

    @XmlAttribute(name = "char")
    protected String alignChar;

    @XmlAttribute(name = "charoff")
    protected String charoff;

}
