//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 04:50:11 PM UTC 
//


package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for xhtml.colgroup.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xhtml.colgroup.type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.w3.org/1999/xhtml}xhtml.colgroup.content"/&gt;
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}xhtml.colgroup.attlist"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.colgroup.type", propOrder = {
    "col"
})
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
public class XhtmlColgroupType {

    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected List<XhtmlColType> col;
    @XmlAttribute(name = "span")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected BigInteger span;
    @XmlAttribute(name = "width")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected List<String> width;
    @XmlAttribute(name = "valign")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String valign;
    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String space;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String id;
    @XmlAttribute(name = "title")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String title;
    @XmlAttribute(name = "class")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String clazz;
    @XmlAttribute(name = "style")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String style;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String lang;
    @XmlAttribute(name = "align")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String align;
    @XmlAttribute(name = "char")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String _char;
    @XmlAttribute(name = "charoff")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String charoff;

    /**
     * Gets the value of the col property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the col property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCol().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XhtmlColType }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public List<XhtmlColType> getCol() {
        if (col == null) {
            col = new ArrayList<XhtmlColType>();
        }
        return this.col;
    }

    /**
     * Gets the value of the span property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public BigInteger getSpan() {
        if (span == null) {
            return new BigInteger("1");
        } else {
            return span;
        }
    }

    /**
     * Sets the value of the span property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setSpan(BigInteger value) {
        this.span = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the width property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWidth().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public List<String> getWidth() {
        if (width == null) {
            width = new ArrayList<String>();
        }
        return this.width;
    }

    /**
     * Gets the value of the valign property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getValign() {
        return valign;
    }

    /**
     * Sets the value of the valign property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setValign(String value) {
        this.valign = value;
    }

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getSpace() {
        if (space == null) {
            return "preserve";
        } else {
            return space;
        }
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setLang(String value) {
        this.lang = value;
    }

    /**
     * Gets the value of the align property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getAlign() {
        return align;
    }

    /**
     * Sets the value of the align property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setAlign(String value) {
        this.align = value;
    }

    /**
     * Gets the value of the char property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getChar() {
        return _char;
    }

    /**
     * Sets the value of the char property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setChar(String value) {
        this._char = value;
    }

    /**
     * Gets the value of the charoff property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getCharoff() {
        return charoff;
    }

    /**
     * Sets the value of the charoff property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setCharoff(String value) {
        this.charoff = value;
    }

}
