//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for xhtml.param.type complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.param.type")
@XmlRootElement(name = "param", namespace = "http://www.w3.org/1999/xhtml")
@Getter
@Setter
public class XhtmlParamType extends XhtmlBasicType {

    @XmlAttribute(name = "name", required = true)
    private String name;

    @XmlAttribute(name = "value")
    private String value;

    @XmlAttribute(name = "valuetype")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    private String valuetype = "data";

    @XmlAttribute(name = "type")
    private String type;

}
