//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlMixed;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
import lombok.AccessLevel;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for xhtml.h3.type complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.h3.type", propOrder = {
    "content"
})
@XmlRootElement(name = "h3", namespace = "http://www.w3.org/1999/xhtml")
@Getter
@Setter
public class XhtmlH3Type extends XhtmlBasicStyleableType {

    @XmlElementRefs({
        @XmlElementRef(type = XhtmlBrType.class, required = false),
        @XmlElementRef(type = XhtmlSpanType.class, required = false),
        @XmlElementRef(type = XhtmlEmType.class, required = false),
        @XmlElementRef(type = XhtmlStrongType.class, required = false),
        @XmlElementRef(type = XhtmlDfnType.class, required = false),
        @XmlElementRef(type = XhtmlCodeType.class, required = false),
        @XmlElementRef(type = XhtmlSampType.class, required = false),
        @XmlElementRef(type = XhtmlKbdType.class, required = false),
        @XmlElementRef(type = XhtmlVarType.class, required = false),
        @XmlElementRef(type = XhtmlCiteType.class, required = false),
        @XmlElementRef(type = XhtmlAbbrType.class, required = false),
        @XmlElementRef(type = XhtmlAcronymType.class, required = false),
        @XmlElementRef(type = XhtmlQType.class, required = false),
        @XmlElementRef(type = XhtmlTtType.class, required = false),
        @XmlElementRef(type = XhtmlIType.class, required = false),
        @XmlElementRef(type = XhtmlBType.class, required = false),
        @XmlElementRef(type = XhtmlBigType.class, required = false),
        @XmlElementRef(type = XhtmlSmallType.class, required = false),
        @XmlElementRef(type = XhtmlSubType.class, required = false),
        @XmlElementRef(type = XhtmlSupType.class, required = false),
        @XmlElementRef(type = XhtmlAType.class, required = false),
        @XmlElementRef(type = XhtmlObjectType.class, required = false),
        @XmlElementRef(type = XhtmlInsType.class, required = false),
        @XmlElementRef(type = XhtmlDelType.class, required = false)
    })
    @XmlMixed
    @Setter(AccessLevel.NONE)
    private List<XhtmlBasicType> content = new ArrayList<>();

}
