from typing import List

from tgen.common.util.dataclass_util import DataclassUtil
from tgen.common.util.param_specs import ParamSpecs
from tgen.common.util.status import Status
from tgen.constants.deliminator_constants import EMPTY_STRING
from tgen.data.tdatasets.prompt_dataset import PromptDataset
from tgen.data.tdatasets.trace_dataset import TraceDataset
from tgen.hgen.hgen_args import HGenArgs
from tgen.jobs.abstract_job import AbstractJob
from tgen.jobs.components.args.job_args import JobArgs
from tgen.jobs.hgen_jobs.base_hgen_job import BaseHGenJob


class MultiLayerHGenJob(AbstractJob):

    def __init__(self, starting_hgen_job: BaseHGenJob, target_types: List[str], job_args: JobArgs = None):
        """
        Initializes the job with args needed for hierarchy generator
        :param starting_hgen_job: The initial hgen job to run to get the first layer of artifacts
        :param target_types: The list of target types going up the hierarchy
        :param job_args: The arguments need for the job
        """
        self.starting_hgen_job = starting_hgen_job
        if len(target_types) > 0 and self.starting_hgen_job.get_hgen_args().target_type == target_types[0]:
            # target types should not include start target type
            target_types.pop(0)
        self.target_types = target_types
        super().__init__(job_args)

    def _run(self) -> TraceDataset:
        """
        Runs all the hgen jobs, slowly progressing up the hierarchy
        :return: The final dataset created by the top level hgen job
        """
        current_hgen_job = self.starting_hgen_job
        current_hgen_job.result.experimental_vars = {"target_type": current_hgen_job.get_hgen_args().target_type}
        for i, next_target_type in enumerate(self.target_types):
            res = current_hgen_job.run()
            if res.status != Status.SUCCESS:
                raise Exception(res.body)
            dataset = res.body
            current_hgen_job = self.get_next_hgen_job(current_hgen_job, next_target_type, dataset)
        return current_hgen_job.run().body

    @staticmethod
    def get_next_hgen_job(current_hgen_job: BaseHGenJob, next_target_type: str, generated_dataset: TraceDataset) -> BaseHGenJob:
        """
        Gets the next hgen job to progress up the hierarchy
        :param current_hgen_job: The last hgen job that run
        :param next_target_type: The next target type to create with the new hgen job
        :param generated_dataset: The dataset generated by the last hgen job run
        :return: The next hgen job
        """
        current_args = current_hgen_job.get_hgen_args()
        new_params = DataclassUtil.convert_to_dict(current_args, source_layer_id=current_args.target_type,
                                                   source_type=current_args.target_type,
                                                   target_type=next_target_type,
                                                   dataset_for_sources=PromptDataset(trace_dataset=generated_dataset),
                                                   system_summary=current_hgen_job.hgen.state.summary,
                                                   load_dir=EMPTY_STRING)
        init_params = ParamSpecs.create_from_method(HGenArgs.__init__).param_names
        new_params = {name: new_params[name] for name in init_params}
        next_job = BaseHGenJob(HGenArgs(**new_params), current_hgen_job.job_args)
        next_job.result.experimental_vars = {"target_type": next_target_type}
        return next_job
