AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AccountId:
    Type: String
    NoEcho: true
    Description: 'ID of account containing ECR repository.'
  StackName:
    Type: String
    NoEcho: true
    Description: 'The name of the entire stack.'
  BucketName:
    Type: String
    Description: "Name of artifact bucket."
  GitHubConnectionArn:
    Type: String
    NoEcho: true
    Description: 'GitHub Connection ARN.'
  GithubRepository:
    Type: String
    NoEcho: true
    Description: 'GitHub repository to build.'
  PipelineRoleArn:
    Type: String
    NoEcho: true
    Description: 'ARN for pipeline role'
  BuildRoleArn:
    Type: String
    NoEcho: true
    Description: 'ARN for build role.'
  Region:
    Type: String
    NoEcho: true
    Description: 'The region ECR repository is located in.'
    Default: 'us-east-1'

Resources:
  ArtifactBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private

  Pipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Ref StackName
      RoleArn: !Ref PipelineRoleArn
      ArtifactStore:
        Location: !Ref ArtifactBucket  # Use the S3 bucket created above
        Type: S3
      Stages:
      - Name: Source
        Actions:
        - Name: SourceAction
          ActionTypeId:
            Category: Source
            Owner: AWS
            Version: 1
            Provider: CodeStarSourceConnection
          OutputArtifacts:
          - Name: SourceOutput
          Configuration:
            ConnectionArn: !Ref GitHubConnectionArn
            FullRepositoryId: !Ref GithubRepository
            BranchName: staging
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: BuildAction
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: 1
            Provider: CodeBuild
          InputArtifacts:
          - Name: SourceOutput
          OutputArtifacts:
          - Name: BuildOutput
          Configuration:
            ProjectName: !Ref StackName
          RunOrder: 1

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref StackName
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: LOCAL
        Modes:
        - LOCAL_DOCKER_LAYER_CACHE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        EnvironmentVariables:
        - Name: ECR_LINK
          Type: PLAINTEXT
          Value: !Sub "${AccountId}.dkr.ecr.${Region}.amazonaws.com"
      ServiceRole: !Ref BuildRoleArn
      Source:
        Type: GITHUB
        Location: !Sub "https://github.com/${GithubRepository}"
        Auth:
          Type: OAUTH
          Resource: !Ref GitHubConnectionArn
        GitSubmodulesConfig:
          FetchSubmodules: true  # Enable fetching submodules
      LogsConfig:
        CloudWatchLogs:
          GroupName: !Ref StackName
          StreamName: !Sub "${StackName}-buildlogs"
          Status: ENABLED

