ALTER TABLE github_access_credentials DROP COLUMN refresh_token;
ALTER TABLE github_access_credentials DROP COLUMN access_token_expiration_date;
ALTER TABLE github_access_credentials DROP COLUMN refresh_token_expiration_date;