//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.XmlValue;
import lombok.Getter;
import lombok.Setter;


/**
 * Java class for ATTRIBUTE-VALUE-ENUMERATION complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ATTRIBUTE-VALUE-ENUMERATION", namespace = "", propOrder = {})
@Getter
@Setter
public class AttributeValueEnumeration extends AttributeValue {

    @XmlElement(name = "DEFINITION", required = true)
    private Definition definition;

    @XmlElement(name = "VALUES")
    private Values values;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeDefinition"
    })
    @Getter
    @Setter
    public static class Definition {
        @XmlElement(name = "ATTRIBUTE-DEFINITION-ENUMERATION-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private AttributeDefinitionEnumeration attributeDefinition;
    }


    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "values"
    })
    @Getter
    public static class Values {
        @XmlElementRef(type = EnumValueRef.class, required = false)
        private List<EnumValueRef> values = new ArrayList<>();
    }

    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlRootElement(name = "ENUM-VALUE-REF", namespace = "")
    @Getter
    @Setter
    public static class EnumValueRef {
        @XmlValue
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private EnumValue enumValue;
    }

}
