//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.math.BigInteger;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlType;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for DATATYPE-DEFINITION-REAL complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DATATYPE-DEFINITION-REAL", namespace = "", propOrder = {})
@Getter
@Setter
public class DatatypeDefinitionReal extends DatatypeDefinition {

    @XmlAttribute(name = "ACCURACY", required = true)
    private BigInteger accuracy;

    @XmlAttribute(name = "MAX", required = true)
    private double max;

    @XmlAttribute(name = "MIN", required = true)
    private double min;
}
