//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for REQ-IF-HEADER complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "REQ-IF-HEADER", namespace = "", propOrder = {
    "comment",
    "creationTime",
    "repositoryId",
    "reqIfToolId",
    "reqIfVersion",
    "sourceToolId",
    "title"
})
@Getter
@Setter
public class ReqIfHeader {

    @XmlElement(name = "COMMENT")
    private String comment;

    @XmlElement(name = "CREATION-TIME", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar creationTime;

    @XmlElement(name = "REPOSITORY-ID")
    private String repositoryId;

    @XmlElement(name = "REQ-IF-TOOL-ID", required = true)
    private String reqIfToolId;

    @XmlElement(name = "REQ-IF-VERSION", required = true)
    private String reqIfVersion;

    @XmlElement(name = "SOURCE-TOOL-ID", required = true)
    private String sourceToolId;

    @XmlElement(name = "TITLE", required = true)
    private String title;

    @XmlAttribute(name = "IDENTIFIER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    private String identifier;
}
