//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.02.27 at 06:07:33 PM UTC
//

package edu.nd.crc.safa.utilities.reqif.datatypes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.datatype.XMLGregorianCalendar;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlAttribute;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlElementRef;
import jakarta.xml.bind.annotation.XmlElementRefs;
import jakarta.xml.bind.annotation.XmlID;
import jakarta.xml.bind.annotation.XmlIDREF;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;
import jakarta.xml.bind.annotation.adapters.CollapsedStringAdapter;
import jakarta.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import lombok.Getter;
import lombok.Setter;

/**
 * Java class for SPEC-HIERARCHY complex type.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SPEC-HIERARCHY", namespace = "", propOrder = {})
@Getter
@Setter
public class SpecHierarchy {

    @XmlElement(name = "ALTERNATIVE-ID")
    private AlternativeIdWrapper alternativeId;

    @XmlElement(name = "CHILDREN")
    private Children children;

    @XmlElement(name = "EDITABLE-ATTS")
    private EditableAttributes editableAttributes;

    @XmlElement(name = "OBJECT", required = true)
    private ObjectRef object;

    @XmlAttribute(name = "DESC")
    private String desc;

    @XmlAttribute(name = "IDENTIFIER", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    private String identifier;

    @XmlAttribute(name = "IS-EDITABLE")
    private Boolean editable;

    @XmlAttribute(name = "IS-TABLE-INTERNAL")
    private Boolean tableInternal;

    @XmlAttribute(name = "LAST-CHANGE", required = true)
    @XmlSchemaType(name = "dateTime")
    private XMLGregorianCalendar lastChange;

    @XmlAttribute(name = "LONG-NAME")
    private String longName;

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "attributeDefinitions"
    })
    @Getter
    public static class EditableAttributes {

        @XmlElementRefs({
            @XmlElementRef(type = AttributeDefinitionBooleanRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionDateRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionEnumerationRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionIntegerRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionRealRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionStringRef.class, required = false),
            @XmlElementRef(type = AttributeDefinitionXhtmlRef.class, required = false)
        })
        private List<AttributeDefinitionRef> attributeDefinitions = new ArrayList<>();
    }

    /**
     * Java class for anonymous complex type.
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "specObject"
    })
    @Getter
    @Setter
    public static class ObjectRef {

        @XmlElement(name = "SPEC-OBJECT-REF", namespace = "")
        @XmlIDREF
        @XmlSchemaType(name = "IDREF")
        private SpecObject specObject;
    }

}
