DEFAULT_REDUCTION_FACTOR = 0.50  # Expected reduction in artifacts
DEFAULT_CLUSTER_SIMILARITY_THRESHOLD = 0.75
DEFAULT_RANDOM_STATE = 0
DEFAULT_TESTING_CLUSTERING_METHODS = ["KMEANS", "AGGLOMERATIVE"]
DEFAULT_CLUSTERING_METHODS = ["OPTICS", "AFFINITY", "SPECTRAL", "KMEANS", "AGGLOMERATIVE"]
DEFAULT_ADD_CLUSTERS_TO_DATASET = False
MAX_CLUSTER_SIZE = 5
MIN_CLUSTER_SIZE = 2
