DEFAULT_REDUCTION_FACTOR = 0.40  # Expected reduction in artifacts
DEFAULT_CLUSTER_SIMILARITY_THRESHOLD = 0.50
DEFAULT_RANDOM_STATE = 0
DEFAULT_TESTING_CLUSTERING_METHODS = ["KMEANS", "AGGLOMERATIVE"]
DEFAULT_CLUSTERING_METHODS = ["BIRCH", "OPTICS", "HB_SCAN"]
DEFAULT_ADD_CLUSTERS_TO_DATASET = False
