TEMPERATURE_ON_RERUNS = 0.4
WEIGHT_OF_PRED_RELATED_CHILDREN = 0.5
DEFAULT_LINK_THRESHOLD = 0.5
DEFAULT_ORPHAN_THRESHOLD = 0.4
DEFAULT_DUPLICATE_SIMILARITY_THRESHOLD = 0.55
RELATED_CHILDREN_SCORE = 0.99
FIRST_PASS_LINK_THRESHOLD = 0.5
