"""
Sections
"""
PS_OVERVIEW_TITLE = "Overview"
PS_OVERVIEW_TAG = "overview"

PS_FEATURE_TITLE = "Features"
PS_FEATURE_TAG = "features"

PS_ENTITIES_TITLE = "Entities"
PS_ENTITIES_TAG = "entities"

PS_SUBSYSTEM_TITLE = "Sub-systems"
PS_SUBSYSTEM_TAG = "sub-system"

PS_DATA_FLOW_TITLE = "Data Flow"
PS_DATA_FLOW_TAG = "data-flow"

PS_QUESTIONS_HEADER = "\n\n# Questions\n"

PS_FILE_NAME = "project_summary.txt"
PS_STATE_FILE_NAME = "project_summary_state.json"

CUSTOM_TITLE_TAG = "title"

"""
Defaults 
"""
PS_NOTES_TAG = "notes"
PS_DEFAULT_SAVE_PROGRESS = True

"""
Mappings
"""
DEFAULT_PROJECT_SUMMARY_SECTIONS = [
    PS_FEATURE_TITLE,
    PS_ENTITIES_TITLE,
    PS_SUBSYSTEM_TITLE,
    PS_DATA_FLOW_TITLE,
    PS_OVERVIEW_TITLE
]

PROJECT_SUMMARY_SECTIONS_DISPLAY_ORDER = [
    PS_OVERVIEW_TITLE,
    PS_FEATURE_TITLE,
    PS_ENTITIES_TITLE,
    PS_SUBSYSTEM_TITLE,
    PS_DATA_FLOW_TITLE
]

PROJECT_SUMMARY_TAGS = {
    PS_OVERVIEW_TITLE: PS_OVERVIEW_TAG,
    PS_FEATURE_TITLE: PS_FEATURE_TAG,
    PS_ENTITIES_TITLE: PS_ENTITIES_TAG,
    PS_SUBSYSTEM_TITLE: PS_SUBSYSTEM_TAG,
    PS_DATA_FLOW_TITLE: PS_DATA_FLOW_TAG
}
