//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0.1 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.02.27 at 04:50:11 PM UTC 
//


package edu.nd.crc.safa.utilities.reqif;

import javax.annotation.Generated;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlID;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for xhtml.hr.type complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="xhtml.hr.type"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;group ref="{http://www.w3.org/1999/xhtml}xhtml.hr.content"/&gt;
 *       &lt;attGroup ref="{http://www.w3.org/1999/xhtml}xhtml.hr.attlist"/&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "xhtml.hr.type")
@Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
public class XhtmlHrType {

    @XmlAttribute(name = "space", namespace = "http://www.w3.org/XML/1998/namespace")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String space;
    @XmlAttribute(name = "id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlID
    @XmlSchemaType(name = "ID")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String id;
    @XmlAttribute(name = "title")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String title;
    @XmlAttribute(name = "class")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String clazz;
    @XmlAttribute(name = "style")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String style;
    @XmlAttribute(name = "lang", namespace = "http://www.w3.org/XML/1998/namespace")
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    protected String lang;

    /**
     * Gets the value of the space property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getSpace() {
        if (space == null) {
            return "preserve";
        } else {
            return space;
        }
    }

    /**
     * Sets the value of the space property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setSpace(String value) {
        this.space = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the clazz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getClazz() {
        return clazz;
    }

    /**
     * Sets the value of the clazz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setClazz(String value) {
        this.clazz = value;
    }

    /**
     * Gets the value of the style property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getStyle() {
        return style;
    }

    /**
     * Sets the value of the style property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setStyle(String value) {
        this.style = value;
    }

    /**
     * Gets the value of the lang property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public String getLang() {
        return lang;
    }

    /**
     * Sets the value of the lang property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    @Generated(value = "com.sun.tools.xjc.Driver", date = "2023-02-27T10:50:11-06:00", comments = "JAXB RI v2.3.0.1")
    public void setLang(String value) {
        this.lang = value;
    }

}
