from dotenv import load_dotenv

load_dotenv()

TEMPERATURE_DEFAULT = 0
MAX_TOKENS_DEFAULT = 512
MAX_TOKENS_BUFFER = 400
LOGPROBS_DEFAULT = 2
LEARNING_RATE_MULTIPLIER_DEFAULT = None
COMPUTE_CLASSIFICATION_METRICS_DEFAULT = True
SUMMARIZATION_MODEL_DEFAULT = "text-davinci-003"
CLASSIFICATION_MODEL_DEFAULT = "ada:ft-safa:cm1-test-2023-03-29-20-25-19"
GENERATION_MODEL_DEFAULT = "text-davinci-003"
