DEFAULT_PARENT_THRESHOLD = 0.80  # The minimum percentile to consider a candidate as true
DEFAULT_PARENT_MIN_THRESHOLD = 0.4  # The minimum percentile allowed for a top parent prediction.
DEFAULT_MIN_RANKING_SCORE = 0.5
DEFAULT_MAX_N_CHILDREN = 50
DEFAULT_SORTING_ALGORITHM = "embedding"
BODY_ARTIFACT_TITLE = "# Software Artifacts\nBelow are the artifact of the software system."
DEFAULT_SUMMARY_TOKENS = 5000
GENERATE_SUMMARY_DEFAULT = True
SUMMARY_TITLE = "# Software Specification"
DEFAULT_QUERY_TAG = "parent-artifact"
DEFAULT_LINKS_TAG = "links"
DEFAULT_RANKING_MODEL = "claude-2.0"
DEFAULT_SEARCH_FILTER = 50
DEFAULT_SEARCH_MODEL = "claude-instant-v1"
SEARCH_PARENT_TYPE = "prompt"
SEARCH_CHILD_TYPE = "artifacts"
DEFAULT_VSM_SELECT_PREDICTION = True
DEFAULT_THRESHOLD_SCORE = 0.6
TIER_ONE_THRESHOLD = 0.8
TIER_TWO_THRESHOLD = 0.7
