DEFAULT_PARENT_THRESHOLD = 0.80  # The minimum percentile to consider a candidate as true
DEFAULT_PARENT_MIN_THRESHOLD = 0.4  # The minimum percentile allowed for a top parent prediction.
DEFAULT_MIN_RANKING_SCORE = 0.5
DEFAULT_MAX_N_CHILDREN = 50
DEFAULT_SORTING_ALGORITHM = "embedding"
DEFAULT_ARTIFACT_HEADER = "Software Artifacts"
BODY_ARTIFACT_TITLE = f"# {DEFAULT_ARTIFACT_HEADER}\nBelow are the artifact of the software system."
DEFAULT_SUMMARY_TOKENS = 20000
DEFAULT_COMPLETION_TOKENS = 20000
GENERATE_SUMMARY_DEFAULT = True
PROJECT_SUMMARY_HEADER = "Software Specification"
DEFAULT_LINKS_TAG = "links"
DEFAULT_RANKING_MODEL = "claude-2.0"
DEFAULT_SEARCH_FILTER = 50
DEFAULT_SEARCH_MODEL = "claude-instant-v1"
SEARCH_PARENT_TYPE = "prompt"
SEARCH_CHILD_TYPE = "artifacts"
DEFAULT_VSM_SELECT_PREDICTION = True
DEFAULT_LINK_THRESHOLD = 0.6
DEFAULT_HGEN_LINK_THRESHOLD = 0.8
DEFAULT_SELECT_TOP_PREDICTIONS = True
DEFAULT_MAX_CONTEXT_ARTIFACTS = 20
PROJECT_SUMMARY_FILE_NAME = f"project_summary.yaml"
RANKING_MIN_SCORE = 1
RANKING_MAX_SCORE = 10
"""
Tags
"""
RANKING_PARENT_TAG = "parent-artifact"
RANKING_ARTIFACT_TAG = "artifact"
RANKING_PARENT_SUMMARY_TAG = "parent-summary"
RANKING_ID_TAG = "id"
RANKING_EXPLANATION_TAG = "explanation"
RANKING_SCORE_TAG = "score"
