DEFAULT_PARENT_THRESHOLD = 0.8  # The minimum percentile to consider a candidate as true
DEFAULT_PARENT_MIN_THRESHOLD = 0.75  # The minimum percentile allowed for a top parent prediction.
DEFAULT_MIN_RANKING_SCORE = DEFAULT_PARENT_MIN_THRESHOLD
DEFAULT_MAX_N_CHILDREN = 50
DEFAULT_SORTING_ALGORITHM = "vsm"
BODY_ARTIFACT_TITLE = "# Software Artifacts\nBelow are the artifact of the software system."
DEFAULT_SUMMARY_TOKENS = 5000
GENERATE_SUMMARY_DEFAULT = True
SUMMARY_TITLE = "# Software Specification"
DEFAULT_QUERY_TAG = "parent-artifact"
DEFAULT_RANKING_MODEL = "claude-2.0"
DEFAULT_SEARCH_FILTER = 50
DEFAULT_SEARCH_MODEL = "claude-instant-v1"
SEARCH_PARENT_TYPE = "prompt"
SEARCH_CHILD_TYPE = "artifacts"
