services:
  gen:
    container_name: gen
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TASK_MANAGER: redis
    env_file: .env
    ports:
    - "4000:80"
    volumes:
    - tgen-volume:/vol
    - ~/.cache/models:/root/.cache/huggingface/datasets
    networks:
    - safa_network
    environment:
    - DEBUG=false
    - ENV_MODE=development
    - N_WORKERS=2
    - DEFAULT_CROSS_ENCODER_MODEL=cross-encoder/ms-marco-TinyBERT-L-2
    - DEFAULT_EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
    - BROKER=redis
    - BROKER_URL=redis://redis:6379/0
    - BROKER_USERNAME=guest
    - BROKER_PASSWORD=guest
    - HF_DATASETS_CACHE=/root/.cache/huggingface/datasets
  redis:
    container_name: redis
    image: redis:alpine
    networks:
    - safa_network

networks:
  safa_network:

volumes:
  tgen-volume:
    name: tgen-volume
