AWSTemplateFormatVersion: '2010-09-09'
Resources:
  EnvReaderManagedPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'envs-reader-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Action:
          - 's3:GetObject'
          - 's3:PutObject'
          - 's3:PutObjectAcl'
          Resource: 'arn:aws:s3:::safa-envs/*'

  ExecutionPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      ManagedPolicyName: 'general-execution-policy'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: 'Allow'
          Action:
          - ec2:*
          - ecs:*
          - elasticfilesystem:*
          - codebuild:*
          - codecommit:*
          - codepipeline:*
          - codestar:*
          - codestar-connections:*
          - cloudwatch:*
          - ecr:*
          - s3:*
          - secretsmanager:*
          - logs:*
          - codedeploy:*
          - appconfig:*
          - states:*
          - cloudformation:*
          - servicecatalog:*
          - devicefarm:*
          - opsworks:*
          - sns:*
          - rds:*
          - sqs:*
          - lambda:*
          - iam:PassRole
          - elasticbeanstalk:*
          - elasticloadbalancing:*
          - autoscaling:*
          - autoscaling-plans:*
          - cloudwatch:*
          - s3:*
          - sns:*
          - cloudformation:*
          - rds:*
          - sqs:*
          - ecs:*
          Resource: "*"
          
        - Effect: 'Allow'
          Action:
          - lambda:InvokeFunction
          - lambda:ListFunctions
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - opsworks:CreateDeployment
          - opsworks:DescribeApps
          - opsworks:DescribeCommands
          - opsworks:DescribeDeployments
          - opsworks:DescribeInstances
          - opsworks:DescribeStacks
          - opsworks:UpdateApp
          - opsworks:UpdateStack
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - cloudformation:CreateStack
          - cloudformation:DeleteStack
          - cloudformation:DescribeStacks
          - cloudformation:UpdateStack
          - cloudformation:CreateChangeSet
          - cloudformation:DeleteChangeSet
          - cloudformation:DescribeChangeSet
          - cloudformation:ExecuteChangeSet
          - cloudformation:SetStackPolicy
          - cloudformation:ValidateTemplate
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - codebuild:BatchGetBuilds
          - codebuild:StartBuild
          - codebuild:BatchGetBuildBatches
          - codebuild:StartBuildBatch
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - devicefarm:ListProjects
          - devicefarm:ListDevicePools
          - devicefarm:GetRun
          - devicefarm:GetUpload
          - devicefarm:CreateUpload
          - devicefarm:ScheduleRun
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - servicecatalog:ListProvisioningArtifacts
          - servicecatalog:CreateProvisioningArtifact
          - servicecatalog:DescribeProvisioningArtifact
          - servicecatalog:DeleteProvisioningArtifact
          - servicecatalog:UpdateProduct
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - cloudformation:ValidateTemplate
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - ecr:DescribeImages
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - states:DescribeExecution
          - states:DescribeStateMachine
          - states:StartExecution
          Resource: '*'

        - Effect: 'Allow'
          Action:
          - appconfig:StartDeployment
          - appconfig:StopDeployment
          - appconfig:GetDeployment
          Resource: '*'
