import { ArtifactSchema } from "@/types";

/**
 * Represents the type of user comment on an artifact.
 */
export type CommentType =
  | "flag" // Resolution is necessary
  | "conversation" // Resolution is optional
  | "contradiction"
  | "suggestion"
  | "undefined_concept"
  | "matched_concept"
  | "multi_matched_concept";

/**
 * Represents the status of a user comment on an artifact.
 */
export type CommentStatus = "active" | "resolved";

/**
 * Represents a user comment on an artifact.
 */
export interface CommentSchema {
  /**
   * Unique identifier for the comment.
   */
  id: string;
  /**
   * The content of the comment.
   */
  content: string;
  /**
   * The user who published the comment.
   * If empty, the comment was generated by SAFA.
   */
  userId?: string;
  /**
   * The status of the comment.
   */
  status: CommentStatus;
  /**
   * The type of the comment.
   */
  type: CommentType;
  /**
   * The date and time the comment was created.
   */
  createdAt: string;
  /**
   * The date and time the comment was last edited.
   */
  updatedAt: string;
}

/**
 * Represents an artifact that has an undefined concept.
 */
interface UndefinedConceptHealthCheck extends CommentSchema {
  type: "undefined_concept";
  undefinedConcept: string;
}

/**
 * Represents a health check on an artifact based on a mentioned concept.
 */
interface ConceptHealthCheckSchema extends CommentSchema {
  type: "matched_concept" | "suggestion";
  /**
   * The name of the concept.
   */
  conceptName: string;
}

/**
 * Represents a health check on an artifact based on a contradiction.
 */
interface ContradictionHealthCheckSchema extends CommentSchema {
  type: "contradiction";
  /**
   * The artifacts affected by the contradiction.
   */
  artifactIds: string[];
}

/**
 * Represents a health check on an artifact based on multiple concepts.
 */
interface MultipleConceptHealthCheckSchema extends CommentSchema {
  type: "multi_matched_concept";
  /**
   * The names of the matched concepts.
   */
  concepts: string[];
}

/**
 * Represents any type of health check on an artifact.
 */
export type AnyCommentSchema =
  | CommentSchema
  | UndefinedConceptHealthCheck
  | ConceptHealthCheckSchema
  | ContradictionHealthCheckSchema
  | MultipleConceptHealthCheckSchema;

/**
 * Represents a collection of health checks on an artifact.
 */
export interface HealthCheckCollectionSchema {
  /**
   * The health checks on the artifact.
   * type = contradiction, suggestion, unknown_concept, matched_concept, multi_matched_concept
   */
  healthChecks: AnyCommentSchema[];
}

/**
 * Represents a collection of comments and flags on an artifact.
 */
export interface ArtifactCommentsSchema extends HealthCheckCollectionSchema {
  /**
   * The unique identifier of the artifact.
   */
  artifactId: string;
  /**
   * The comments on the artifact.
   * type = conversation
   */
  comments: CommentSchema[];
  /**
   * The flags on the artifact.
   * type = flag
   */
  flags: CommentSchema[];
}
