AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  VpcId:
    Type: String
    Description: VPC ID where endpoints should be created

  SubnetId1:
    Type: String
    Description: Subnet ID for us-east-1a

  SubnetId2:
    Type: String
    Description: Subnet ID for us-east-1b

  SubnetId3:
    Type: String
    Description: Subnet ID for us-east-1c

  SecurityGroupId:
    Type: String
    Description: Security Group ID to attach

Resources:
  S3Endpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.s3
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true

  ECREndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.ecr.dkr
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true

  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.secretsmanager
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true

  CloudWatchLogsEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.logs
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true

  ECRAPIDockerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.ecr.api
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true

  EFSEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: com.amazonaws.us-east-1.elasticfilesystem
      VpcEndpointType: Interface
      SecurityGroupIds:
      - !Ref SecurityGroupId
      SubnetIds:
      - !Ref SubnetId1
      - !Ref SubnetId2
      - !Ref SubnetId3
      PrivateDnsEnabled: true
