name: Cypress Tests

on:
  push:
    branches:
      - production
      - development
  pull_request:
    branches:
      - production
      - development

jobs:
  lint-run:
    name: Lint Checker
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
  cypress-run:
    name: Cypress E2E Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install certificates
        run: >
          sudo apt install libnss3-tools;
          curl -JLO "https://dl.filippo.io/mkcert/latest?for=linux/amd64";
          chmod +x mkcert-v*-linux-amd64;
          sudo cp mkcert-v*-linux-amd64 /usr/local/bin/mkcert;
          mkcert -install;
          cd certs;
          mkcert localhost.safa.ai

      - name: Add hosts to /etc/hosts
        run: sudo sed -i "2i 127.0.0.1 localhost.safa.ai" /etc/hosts

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          start: npm start
          wait-on: 'https://localhost.safa.ai:8080'
          browser: chrome
          headed: true
        env:
          DEBUG: '@cypress/github-action'
          NODE_TLS_REJECT_UNAUTHORIZED: 0
